version: "3"

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - 8000:8000
      - 5005:5005
    volumes:
      - "~/.ivy2:/root/.ivy2"
      - "~/.sbt:/root/.sbt"
      - "./api-gateway:/opt/api-gateway"
      - "/opt/api-gateway/target"
    depends_on:
      - mongo-database
      - redis-kv-store
    environment:
      MONGO_DB_URL: "mongodb://mongo-database:27017"
      REDIS_HOST: "redis-kv-store"
      REDIS_PORT: "6379"

  product-service:
    build: ./product-service
    ports:
      - 8001:8000
      - 5006:5005
    depends_on:
      - api-gateway
      - postgres-database
    volumes:
      - "~/.ivy2:/root/.ivy2"
      - "~/.sbt:/root/.sbt"
      - "./product-service:/opt/product-service"
      - "/opt/product-service/target"

  postgres-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asp_rubber

  mongo-database:
    image: mongo
    ports:
      - 27017:27017

  redis-kv-store:
    image: redis
    ports:
      - 6379:6379