version: "3"

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - 8000:8000
      - 5005:5005
    volumes:
      - "~/.ivy2:/root/.ivy2"
      - "~/.sbt:/root/.sbt"
      - "./api-gateway:/opt/api-gateway"
      - "/opt/api-gateway/target"
    depends_on:
      - mongo-database
      - redis-kv-store
    environment:
      MONGO_DB_URL: "mongodb://mongo-database:27017"
      REDIS_HOST: "redis-kv-store"
      REDIS_PORT: "6379"

  mongo-database:
    image: mongo
    ports:
      - 27017:27017

  redis-kv-store:
    image: redis
    ports:
      - 6379:6379